"""update itinerary model

Revision ID: 65d6f793d8b5
Revises: 172b49b560ad
Create Date: 2026-07-17 11:51:07.639466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d6f793d8b5'
down_revision: Union[str, Sequence[str], None] = '172b49b560ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'itineraries',
        sa.Column(
            'generated_by_ai',
            sa.Boolean(),
            server_default=sa.false(),
            nullable=False,
        ),
    )
    op.add_column(
        'itineraries',
        sa.Column(
            'version',
            sa.Integer(),
            server_default='1',
            nullable=False,
        ),
    )
    op.add_column('itineraries', sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itineraries', 'last_generated_at')
    op.drop_column('itineraries', 'version')
    op.drop_column('itineraries', 'generated_by_ai')
    # ### end Alembic commands ###
