"""add budgets table

Revision ID: 75767b60018f
Revises: 4c3f7fe2f0f3
Create Date: 2026-07-20 10:48:51.783496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75767b60018f'
down_revision: Union[str, Sequence[str], None] = '4c3f7fe2f0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('accommodation_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transport_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('food_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activities_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shopping_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('misc_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_trip_id'), 'budgets', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_trip_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
